to_do/urls.py
from django.urls import path

from to_do.views import (
    TodoListView,
    TOdoCreateView,
    TOdoUpdateView,
    TOdoDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_complete_task
)

urlpatterns = [
    path("", TodoListView.as_view(), name="index"),
    path("todos/create/", TOdoCreateView.as_view(), name="to-do-create"),
    path(
        "todos/<int:pk>/update/",
        TOdoUpdateView.as_view(),
        name="to-do-update"
    ),
    path(
        "todos/<int:pk>/delete/",
        TOdoDeleteView.as_view(),
        name="to-do-delete"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "todos/<int:pk>/toggle-complete/",
        toggle_complete_task,
        name="toggle-complete",
    ),
]

app_name = "to_do"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("to_do.urls", namespace="to_do")),
]

to_do/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Todo(models.Model):
    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True, default=None)
    is_done = models.BooleanField(default=False)
    tag = models.ManyToManyField(Tag, related_name="todos")

    class Meta:
        ordering = (
            "is_done",
            "-created",
        )

    def __str__(self):
        return f"{self.content}, created: {self.created}"

to_do/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from to_do.models import Todo, Tag


class TodoCreateForm(forms.ModelForm):
    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Todo
        fields = ["content", "deadline", "tag"]

    def clean_deadline(self):
        data = self.cleaned_data["deadline"]
        if data:
            if data < timezone.now():
                raise ValidationError("Deadline can't be less than now")
        return data


class TaskSearchForm(forms.Form):
    content = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by content"}),
    )


class TagSearchForm(forms.Form):
    name = forms.CharField(
        max_length=20,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )

to_do/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from to_do.forms import TodoCreateForm, TaskSearchForm, TagSearchForm
from to_do.models import Tag, Todo


class TodoListView(generic.ListView):
    model = Todo
    template_name = "to_do/index.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TodoListView, self).get_context_data(**kwargs)
        content = self.request.GET.get("content", "")
        context["search_form"] = TaskSearchForm(initial={"content": content})
        return context

    def get_queryset(self):
        queryset = Todo.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(content__icontains=form.cleaned_data["content"])
        return queryset


class TOdoCreateView(generic.CreateView):
    model = Todo
    form_class = TodoCreateForm
    success_url = reverse_lazy("to_do:index")


class TOdoUpdateView(generic.UpdateView):
    model = Todo
    form_class = TodoCreateForm
    success_url = reverse_lazy("to_do:index")


class TOdoDeleteView(generic.DeleteView):
    model = Todo
    success_url = reverse_lazy("to_do:index")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 10
    fields = "__all__"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TagSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Tag.objects.all()
        form = TagSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("to_do:tag-list")


def toggle_complete_task(request, pk):
    task = Todo.objects.get(id=pk)
    task.is_done = not task.is_done
    task.save()
    return HttpResponseRedirect(reverse_lazy("to_do:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To do</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% block pagination %}

  {% if is_paginated %}
    <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
      <nav aria-label="Page navigation example">
        <ul class="pagination mb-0">
          <li class="page-item {% if not page_obj.has_previous %}disabled {% endif %}">
            <a href="{% if page_obj.has_previous %}?{% query_transform request page=page_obj.previous_page_number %}
{% else %}#{% endif %}"
               class="page-link"><span aria-hidden="true">&laquo;</span></a>
          </li>
          <li class="page-item {% if not page_obj.has_previous %}disabled {% endif %}">
            <a href="{% if page_obj.has_previous %}?{% query_transform request page=page_obj.previous_page_number %}
{% else %}#{% endif %}"
               class="page-link">
              {% if page_obj.has_previous %}{{ page_obj.previous_page_number }} {% else %}1 {% endif %}
            </a>
          </li>
          <li class="page-item disabled"><a class="page-link" href="#" style="">Current {{ page_obj.number }}</a></li>
          <li class="page-item {% if not page_obj.has_next %}disabled {% endif %}">
            <a href="{% if page_obj.has_next %}?{% query_transform request page=page_obj.next_page_number %}
{% else %}#{% endif %}"
               class="page-link">
              {% if page_obj.has_next %}{{ page_obj.next_page_number }} {% else %}{{ paginator.num_pages }} {% endif %}
            </a>
          </li>
          <li class="page-item {% if not page_obj.has_next %}disabled {% endif %}">
            <a href="{% if page_obj.has_next %}?{% query_transform request page=page_obj.next_page_number %}
{% else %}#{% endif %}"
               class="page-link"><span aria-hidden="true">&raquo;</span></a>
          </li>
        </ul>
      </nav>
      <div class="fw-normal small mt-4 mt-lg-0">
        Page <b>{{ page_obj.number }}</b> out of <b>{{ paginator.num_pages }}</b> existing
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group" style="margin-top: 30px">
  <li class="list-group-item"><a href="{% url 'to_do:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'to_do:tag-list' %}">Tags</a></li>
</ul>

templates/to_do/index.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="vh-1000" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3" style="width: 120%;">
            <div class="card-body p-4">

              <h4 class="text-center my-3 pb-3">
                To Do List
                <a href="{% url 'to_do:to-do-create' %}" class="btn btn-outline-secondary active, add"
                   style="margin-left: 50px">
                  Add task
                </a>
              </h4>
              <form method="get" action="" class="form-inline">
                {{ search_form|crispy }}
                <input class="btn btn-light" type="submit" value="🔎">
              </form>

              {% for do in todo_list %}
                <table class="table mb-4" style="padding-bottom: 5px; padding-top: 5px; border: 1px solid grey;">
                  <tr>
                    <td>
                      <strong>{{ do.content }}</strong>
                      <span style="color: {% if do.is_done %}green{% else %}red{% endif %}">
                        {% if do.is_done %}Done{% else %}Not done{% endif %}
                      </span>
                    </td>
                    <td>
                      {% if not do.is_done %}
                        <a href="{% url 'to_do:toggle-complete' pk=do.id %}"
                           class="btn btn-outline-success link-to-page" style="float: right">
                          Complete
                        </a>
                      {% else %}
                        <a href="{% url 'to_do:toggle-complete' pk=do.id %}"
                           class="btn btn-outline-secondary link-to-page" style="float: right">
                          Undo
                        </a>
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <a href="{% url 'to_do:to-do-update' pk=do.id %}" class="btn btn-sm btn-outline-secondary">
                        Update task
                      </a>
                      <a href="{% url 'to_do:to-do-delete' pk=do.id %}" class="btn btn-sm btn-outline-danger">
                        Delete task
                      </a>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      Created: {{ do.created }}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <strong>Deadline: </strong>{{ do.deadline }}
                    </td>
                  </tr>
                  <tr>
                    <td>

                      Tags: {% for tag in do.tag.all %}
                      {{ tag.name }},
                    {% endfor %}
                    </td>
                  </tr>
                </table>
                {% empty %} <h3>Here isn't any task to do</h3>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/to_do/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Delete tag</h1>
  <p>Do you want to delete tag: {{ tag.name }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Yes, delete" class="btn btn-outline-danger"/>
    <a href="{% url 'to_do:tag-list' %}" class="btn btn-outline-secondary">Go back</a>
  </form>
{% endblock %}

templates/to_do/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="fild">
    <h1>Hi, {{ object|yesno:"update,add" }} your tag</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-outline-dark" type="submit" value="Submit">
      <a href="{% url 'to_do:tag-list' %}" class="btn btn-outline-secondary">Go back</a>
    </form>
  </div>
{% endblock %}

templates/to_do/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="margin-top: 20px;">
    Tags
    <a href="{% url 'to_do:tag-create' %}" class="btn btn-outline-primary link-to-page" style="float: right;">
      Create tag
    </a>
  </h1>
    <form method="get" action="" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-light" type="submit" value="🔎">
    </form>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'to_do:tag-update' pk=tag.id %}" class="btn btn-sm btn-outline-secondary">
              Update tag
            </a>
          </td>
          <td>
            <a href="{% url 'to_do:tag-delete' pk=tag.id %}" class="btn btn-sm btn-outline-danger">
              Delete tag
            </a>
          </td>
        </tr>
        {% empty %} <h3>Here isn't ant tags</h3>
      {% endfor %}

    </table>
  {% else %}
    <p>Your tag list is empty.</p>
  {% endif %}
{% endblock %}

templates/to_do/todo_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Delete task</h1>
  <p>Do you want to delete task: {{ todo.content }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Yes, delete" class="btn btn-outline-danger"/>
    <a href="{% url 'to_do:index' %}" class="btn btn-outline-secondary">Go back</a>
  </form>
{% endblock %}

templates/to_do/todo_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="fild">
    <h1>Hi, {{ object|yesno:"update,add" }} your task</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-outline-dark" type="submit" value="Submit">
      <a href="{% url 'to_do:index' %}" class="btn btn-outline-secondary">Go back</a>
    </form>
  </div>
{% endblock %}